// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceHostSettings } from "./ServiceHostSettings";

export interface AllServiceSettings { user?: ServiceHostSettings, member?: ServiceHostSettings, }