// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentId } from "./AssignmentId";
import type { GroupId } from "./GroupId";

export interface Assignment { id: AssignmentId, groupId: GroupId, name: string, originTime: any, dueDate: any, }