// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceHostScope } from "./ServiceHostScope";

export interface AuthorizedServiceHost { url: string, id: string, visibility: ServiceHostScope, }