// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { RoleId } from "./RoleId";

export interface BrowserClientState { roleId: RoleId, projectId: ProjectId, }