// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublishState } from "./PublishState";

export interface ChangeGalleryData { name?: string, state?: PublishState, }