// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserClientState } from "./BrowserClientState";
import type { ExternalClientState } from "./ExternalClientState";

export type ClientState = { "browser": BrowserClientState } | { "external": ExternalClientState };