// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitationState } from "./InvitationState";
import type { ProjectId } from "./ProjectId";

export interface CollaborationInvite { id: string, sender: string, receiver: string, projectId: ProjectId, state: InvitationState, createdAt: any, }