// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { RoleData } from "./RoleData";
import type { SaveState } from "./SaveState";

export interface CreateProjectData { owner?: string, name: string, roles?: Array<RoleData>, clientId?: ClientId, saveState?: SaveState, }