// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Name } from "./Name";
import type { ServiceHost } from "./ServiceHost";

export interface CreateGroupData { name: Name, servicesHosts?: Array<ServiceHost>, }