// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { RoleData } from "./RoleData";
import type { RoleId } from "./RoleId";
import type { SaveState } from "./SaveState";

export interface CreateProjectData { owner: string | null, name: string, roles: Array<RoleData> | null, clientId: ClientId | null, saveState: SaveState | null, roleDict: Record<RoleId, RoleData> | null, }