// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Credentials = { "Snap": { username: string, password: string, } } | { "NetsBlox": { username: string, password: string, } };