// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendLinkState } from "./FriendLinkState";

export interface FriendLink { id: string, sender: string, recipient: string, state: FriendLinkState, createdAt: any, updatedAt: any, }