// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FriendInvite { id: string, sender: string, recipient: string, createdAt: any, }