// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalleryId } from "./GalleryId";
import type { ProjectId } from "./ProjectId";
import type { S3Key } from "./S3Key";

export interface GalleryProjectMetadata { galleryId: GalleryId, id: ProjectId, owner: string, name: string, updated: any, originTime: any, thumbnail: string, versions: Array<S3Key | null>, }