// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalleryId } from "./GalleryId";
import type { PublishState } from "./PublishState";

export interface Gallery { id: GalleryId, owner: string, name: string, state: PublishState, }