// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GalleryId } from "./GalleryId";
import type { ProjectId } from "./ProjectId";
import type { Version } from "./Version";

export interface GalleryProjectMetadata { galleryId: GalleryId, id: ProjectId, owner: string, name: string, originTime: any, versions: Array<Version>, }