// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface NetworkTraceMetadata { id: string, startTime: any, endTime?: any | null, }