// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { UserRole } from "./UserRole";

export interface NewUser { username: string, email: string, password?: string, groupId?: GroupId, role?: UserRole, }