// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleId } from "./RoleId";

export interface OccupantInviteData { username: string, roleId: RoleId, sender?: string, }