// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { PublishState } from "./PublishState";
import type { RoleData } from "./RoleData";
import type { RoleId } from "./RoleId";
import type { SaveState } from "./SaveState";

export interface Project { id: ProjectId, owner: string, name: string, updated: any, state: PublishState, collaborators: Array<string>, originTime: any, saveState: SaveState, roles: Record<RoleId, RoleData>, }