// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkTraceMetadata } from "./NetworkTraceMetadata";
import type { ProjectId } from "./ProjectId";
import type { PublishState } from "./PublishState";
import type { RoleId } from "./RoleId";
import type { RoleMetadata } from "./RoleMetadata";
import type { SaveState } from "./SaveState";

export interface ProjectMetadata { id: ProjectId, owner: string, name: string, updated: any, state: PublishState, collaborators: Array<string>, networkTraces: Array<NetworkTraceMetadata>, originTime: any, saveState: SaveState, roles: Record<RoleId, RoleMetadata>, }