// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Names } from "./Names";

export interface RoleMetadata { name: Names, code: string, media: string, }