// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3Key } from "./S3Key";

export interface RoleMetadata { name: string, code: S3Key, media: S3Key, }