// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OccupantState } from "./OccupantState";

export interface RoleState { name: string, occupants: Array<OccupantState>, }