// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleData } from "./RoleData";

export interface RoleDataResponse { id: string, data: RoleData, }