// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { RoleId } from "./RoleId";
import type { RoleState } from "./RoleState";

export interface RoomState { id: ProjectId, owner: string, name: string, roles: Record<RoleId, RoleState>, collaborators: Array<string>, version: bigint, }