// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientId } from "./ClientId";
import type { ClientState } from "./ClientState";
import type { ProjectId } from "./ProjectId";
import type { RoleId } from "./RoleId";

export type SendMessageTarget = { "address": { address: string, } } | { "room": { projectId: ProjectId, } } | { "role": { projectId: ProjectId, roleId: RoleId, } } | { "client": { state?: ClientState, clientId: ClientId, } };