// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendMessageSender } from "./SendMessageSender";
import type { SendMessageTarget } from "./SendMessageTarget";

export interface SendMessage { sender: SendMessageSender | null, target: SendMessageTarget, content: object, }