// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientState } from "./ClientState";
import type { ProjectId } from "./ProjectId";

export interface SentMessage { projectId: ProjectId, recipients: Array<ClientState>, time: any, source: ClientState, content: any, }