// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiKey } from "./ApiKey";

export interface ServiceSettings { apiKeys?: Record<string, ApiKey>, misc?: Record<string, string>, }