// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";

export interface ServiceSettings { user?: string, member?: string, groups: Record<GroupId, string>, }