// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceName } from "./ServiceName";
import type { ServiceSettings } from "./ServiceSettings";

export type ServiceHostSettings = Record<ServiceName, ServiceSettings>;