// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingVisiblity } from "./SettingVisiblity";

export interface SettingValue { value: string, visibility: SettingVisiblity, }