// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssignmentId } from "./AssignmentId";
import type { SubmissionId } from "./SubmissionId";

export interface Submission { id: SubmissionId, assignmentId: AssignmentId, owner: string, originTime: any, }