// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupId } from "./GroupId";
import type { LinkedAccount } from "./LinkedAccount";
import type { ServiceHost } from "./ServiceHost";
import type { UserRole } from "./UserRole";

export interface User { username: string, email: string, groupId?: GroupId, role: UserRole, linkedAccounts: Array<LinkedAccount>, servicesHosts?: Array<ServiceHost>, }