// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3Key } from "./S3Key";

export interface Version { key: S3Key, updated: any, deleted: boolean, }