FROM rust:1.61.0 as builder
WORKDIR /usr/src/netsblox
COPY . .
RUN cargo install --path crates/migrate --locked

FROM debian:bullseye-slim
COPY --from=builder /usr/local/cargo/bin/netsblox-migrate /usr/local/bin/netsblox-migrate
CMD ["netsblox-migrate"]
